WebBanThuoc/WebBanThuoc.Web/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using WebBanThuoc.Data.Reponsitory.Admin;
using WebBanThuoc.Data.ViewModels.User;

namespace WebBanThuoc.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
   
    public class UserController : Controller
    {
        UserRepository repo;
        public UserController()
        {
            repo = new UserRepository();
        }
        public IActionResult SignUp()=>View();
        [HttpPost]
        public async Task<IActionResult> SignUp(AddUserVM addUserVM)
        {
            try
            {
                await repo.SingUp(addUserVM);
                return Ok(true);
               
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                return Ok();
            }
        }
        public IActionResult CheckUser(string username)
        {
            var data=repo.CheckUser(username);
            if (data!=null)
            {
                return Ok(true);
            }
            else
            {
                return Ok(false);
            }

        }
        public IActionResult Login() => PartialView();
        [HttpPost]
        public async Task<IActionResult> Login(LoginVM model)
        {
            model.UserName = model.UserName.Replace(" ", "").ToLower();
            var user = repo.AsNo(model.UserName);
            if (user != null)
            {
                HMACSHA512 hmac = new HMACSHA512();
                hmac.Key = user.PassworkSalt;
                var pwByte = Encoding.UTF8.GetBytes(model.Password);
                var pwHash = hmac.ComputeHash(pwByte);
                if (pwHash.SequenceEqual(user.PassworkHash))
                {
                    var claims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.NameIdentifier,user.Id.ToString()),
                        new Claim(ClaimTypes.Name,user.UserName),
                        new Claim(ClaimTypes.GivenName,user.HoTen),
                        new Claim(ClaimTypes.Role,user.IsAdmin ?"Admin":"Member")
                    };
                    var claimsIdentity = new ClaimsIdentity(claims, "Cookies");
                    var principal = new ClaimsPrincipal(claimsIdentity);
                    var authProperty = new AuthenticationProperties
                    {
                        ExpiresUtc = DateTime.UtcNow.AddHours(6),
                        IsPersistent = model.Check
                    };
                    await HttpContext.SignInAsync("Cookies", principal, authProperty);
                    if (user.IsAdmin)
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home", new { area = "" });
                    }
                }
            }
            else
            {

            }
            return RedirectToAction(nameof(Login));
        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync("Cookies");
            return RedirectToAction("Index", "Home", new { area = "" });
        }
    }
}

WebBanThuoc/WebBanThuoc.Web/Controllers/DonHangController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using WebBanThuoc.Data;
using WebBanThuoc.Data.ViewModels.DatHang;
using WebBanThuoc.DTOs;
using X.PagedList;

namespace WebBanThuoc.Web.Controllers
{
    public class DonHangController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [Authorize]
        public IActionResult DatHang()
        {
            return PartialView();
        }
        [HttpPost]
        public async Task<IActionResult>DatHang(DatHangVM data)
        {
            WebBanThuocDbContext db=new WebBanThuocDbContext();
            DonHang donHang = new DonHang();
            donHang.TenKH = data.TenKH;
            donHang.DiaChi = data.DiaChi;
            donHang.SDT = data.SDT;
            donHang.ngaydat = data.ThoiGianDatHang;
            donHang.IdTaiKhoan = Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var cookieList = Request.Cookies.Where(x => x.Key.Contains("products_"))
               .ToList();
            List<ChiTietDonHang> chiTietDonDatHangList = new List<ChiTietDonHang>();
            foreach (var item in cookieList)
            {
                try
                {
                    int currentID = Convert.ToInt32(item.Key.Replace("products_", ""));
                    Thuoc thisProduct = db.thuocs.Find(currentID);
                    ChiTietDonHang chiTietDonDatHang = new ChiTietDonHang()
                    {
                        IdThuoc = currentID,
                        SoLuong = Convert.ToInt32(item.Value)
                    };
                    thisProduct.DaBan = thisProduct.DaBan+ chiTietDonDatHang.SoLuong;
                    db.thuocs.Update(thisProduct);
                    chiTietDonDatHang.Gia = thisProduct.GiaTien * chiTietDonDatHang.SoLuong;
                    chiTietDonDatHangList.Add(chiTietDonDatHang);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                    continue;
                }
            }
            donHang.chiTietDonHangs = chiTietDonDatHangList;
            double tamTinh = 0;
            foreach (var item in donHang.chiTietDonHangs)
            {
                tamTinh += item.Gia;
            }
            donHang.TongSoTien = Convert.ToInt32(tamTinh);
            await db.AddAsync(donHang);
            await db.SaveChangesAsync();
            return Ok(true);
            }
        public IActionResult ListCartofUser(int page = 1)
        {
            WebBanThuocDbContext db = new WebBanThuocDbContext();
            var idUser = Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var data = db.donHangs
               .Where(x => x.IdTaiKhoan == idUser)
               .Include(x => x.chiTietDonHangs)
               .OrderByDescending(u => u.Id)
               .ToPagedList(page, 3);
            foreach (var item in data)
            {
                foreach (var itemps in item.chiTietDonHangs)
                {
                    var monan = db.thuocs.Find(itemps.IdThuoc);
                    itemps.thuoc = monan;
                }
            }
            return View(data);
        }

    }
}

WebBanThuoc/WebBanThuoc.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - WebBanThuoc.Web</title>
	<link href="~/client/css/style.css" rel="stylesheet" />

	<link href="~/client/css/bootstrap.min.css" rel="stylesheet" />
	<link href="~/client/css/font-awesome.min.css" rel="stylesheet" />
	<link href="~/client/css/animate.css" rel="stylesheet" />
	<link href="~/client/css/owl.carousel.css" rel="stylesheet" />
	<link href="~/client/css/owl.theme.default.min.css" rel="stylesheet" />
	<link href="~/client/css/tooplate-style.css" rel="stylesheet" />
	<style>
		.bg-success-important{
			background-color: green!important;
		}
	</style>
</head>
<body id="top" data-spy="scroll" data-target=".navbar-collapse" data-offset="50">
	<!-- PRE LOADER -->
	<section class="preloader">
		<div class="spinner">

			<span class="spinner-rotate"></span>

		</div>
	</section>


	<!-- HEADER -->
	<header>
		<div class="container">
			<div class="row">

				<div class="col-md-4 col-sm-5">
					<p>Welcome to a Professional Health Care</p>
				</div>

				<div class="col-md-8 col-sm-7 text-align-right">
					<span class="phone-icon"><i class="fa fa-phone"></i> 0842142478	</span>
					<span class="date-icon"><i class="fa fa-calendar-plus-o"></i> 6:00 AM - 10:00 PM (Mon-Fri)</span>
					<span class="email-icon"><i class="fa fa-envelope-o"></i> <a href="#">lephuc300101@gmai.com</a></span>
				</div>

			</div>
		</div>
	</header>
	<section class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="container">

			<div class="navbar-header">
				<button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon icon-bar"></span>
					<span class="icon icon-bar"></span>
					<span class="icon icon-bar"></span>
				</button>

				<!-- lOGO TEXT HERE -->
				<a href="index.html" class="navbar-brand" style="color:forestgreen">Nhà thuốc Phúc/Tín</a>
			</div>

			<!-- MENU LINKS -->
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav navbar-right">
					
					@if (User.Identity.IsAuthenticated)
					{
					 <li>
						<a class="dropdown-toggle smoothScroll" data-toggle="dropdown" aria-expanded="false">
						Tài khoản
						</a>
						<div class="dropdown-menu">
							<a class="dropdown-item" asp-action="ListCartofUser" asp-controller="DonHang">Đơn hàng của bạn</a>
							<a class="dropdown-item" asp-action="Logout" asp-controller="User" asp-area="Admin">Đăng xuất</a>
						</div>
					 </li>
					}
					else
					{
						<li><a asp-action="Login" asp-controller="User" asp-area="Admin" class="smoothScroll">Đăng nhập</a></li>
					}
					
					<li class="appointment-btn cart"><a class="fa fa-cart-arrow-down">Giỏ hàng</a></li>
				</ul>
			</div>

		</div>
	</section>

	<section class="card showcart">
		<i class="fa fa-times" aria-hidden="true" style="float:left"></i>
		<h2>Giỏ hàng</h2>
		<form action="">
			<table>
				<thead>
					<tr>
						<th>Sản phẩm</th>
						<th>Giá</th>
						<th>SL</th>
						<th>Giá</th>
					</tr>
				</thead>
				<tbody id="cart-body">
					<!--
					<tr>
						<td style="display: flex; align-items: center;"><img style="width:70px" src="https://cdn.tgdd.vn/Products/Images/42/230529/iphone-13-pro-max-sierra-blue-600x600.jpg" alt="">Iphone13</td>
						<td> <p><span>300.000</span><sup>đ</sup></p></td>
						<td><input style="width:30px;outline:none;" type="number" value="1" min="1"></td>
						<td style="cursor: pointer;">Xóa</td>
					</tr> -->
				</tbody>
			</table>
			<div style="text-align: right;" class="price-total">
				<p style="font-weight: bold;">Tổng tiền: <span>0</span><sup>đ</sup></p>
			</div>
			<button asp-action="DatHang" asp-controller="DonHang">Đặt hàng</button>
		</form>
	</section>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer data-stellar-background-ratio="5">
		<div class="container">
			<div class="row">

				<div class="col-md-4 col-sm-4">
					<div class="footer-thumb">
						<h4 class="wow fadeInUp" data-wow-delay="0.4s">Liên lạc với chúng tôi</h4>
						<p>Liên lạc với chúng tôi để nhận được sự tư vấn và hỗ trợ tốt nhất</p>

						<div class="contact-info">
							<p><i class="fa fa-phone"></i>0842142478</p>
							<p><i class="fa fa-envelope-o"></i> <a href="#">lephuc300101@gmai.com</a></p>
						</div>
					</div>
				</div>

				

				<div class="col-md-4 col-sm-4">
					<div class="footer-thumb">
						<div class="opening-hours">
							<h4 class="wow fadeInUp" data-wow-delay="0.4s">Ngày mở cửa</h4>
							<p>Thứ 2 - Thứ 6 <span>06:00 AM - 10:00 PM</span></p>
							<p>Thứ 7 <span>09:00 AM - 08:00 PM</span></p>
							<p>Chủ nhật <span>Đóng cửa</span></p>
						</div>

						<ul class="social-icon">
							<li><a href="https://www.facebook.com/profile.php?id=100012678340486" class="fa fa-facebook-square" attr="facebook icon"></a></li>
							<li><a href="https://www.instagram.com/tin_thanhpham/" class="fa fa-instagram"></a></li>
						</ul>
					</div>
				</div>

				<div class="col-md-12 col-sm-12 border-top">
					<div class="col-md-4 col-sm-6">
						<div class="copyright-text">
							<p>
								Phát triển bởi &copy; 2018 Your Company

								| Design: <a rel="nofollow" href="https://www.facebook.com/tooplate" target="_parent">Tooplate</a>
							</p>
						</div>
					</div>
					
				</div>

			</div>
		</div>
	</footer>
	<script src="~/client/js/main.js" asp-append-version="true"></script>
	<script src="~/client/js/jquery.js"></script>
	<script src="~/client/js/bootstrap.min.js"></script>
	<script src="~/client/js/jquery.sticky.js"></script>
	<script src="~/client/js/jquery.stellar.min.js"></script>
	<script src="~/client/js/wow.min.js"></script>
	<script src="~/client/js/smoothscroll.js"></script>
	<script src="~/client/js/owl.carousel.min.js"></script>
	<script src="~/client/js/custom.js"></script>
	<script src="~/client/js/cart/cart.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebBanThuoc/WebBanThuoc.Web/Views/Shared/_Pager.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core
@using X.PagedList.Web.Common

@{
	string _params = "";
	foreach (var item in Context.Request.Query)
	{
		if (item.Key != "page")
		{
			_params += $"&{item.Key}={item.Value}";
		}
	}
}
<div class="my-4">
	@Html.PagedListPager((IPagedList)Model,
		page => Url.Action(ViewContext.RouteData.Values["action"].ToString(), new { page = page }) + _params,
		new PagedListRenderOptions
		{
			LiElementClasses = new string[] { "page-item" },
			PageClasses = new string[] { "bg-success-important", "page-link" },
		})
</div>